### ISSUE TITLE
Error about h5py   

### ISSUE THREAD

**Issue by zjy1128** [asingh33/CNNGestureRecognizer#43] opened 2019-04-25 03:25 UTC
@asingh33  Thank you very much for your information,I download the model from google but I got an error in using it.I don't know how to solve it.
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
TypeError: Indexing elements must be in increasing order
My version:numpy 1.13.1  
                   h5py 2.9.0
                   win10
                   tensorflow 1.2.1
                   keras 2.0.2
                   python3.6.1
what's your version of h5py and numpy?Would you please tell me how to solve the error above?

**Comment by nekomiao123** [comment] 2019-05-07 06:43
I have the same problem. I think there might be something wrong with the .hdf5 document on Google Drive. So the solution is that you can train a new model.  It means you can choose the second choice.

**Comment by asingh33** [comment] 2019-05-14 15:48
@zjy1128 
Did your issue get resolved after doing retraining ?

**Comment by jhonatantirado** [comment] 2019-05-24 20:22
I was able to run the trackgesture.py script after downloading the file ori_4015imgs_weights.hdf5 from Google Drive. I choose option 1: Use pretrained model for gesture recognition & layer visualization. The app opens, I press "g" to toggle Prediction Mode and the camera starts tracking my hands, but the predicition is always NOTHING. I switched between Binary and Skin Mask Mode. Maybe that's because the background in my office is not empty, or there's not enough light. I'll try again at home. Hope that fixes the issue.

**Comment by asingh33** [comment] 2019-06-13 12:53
@zjy1128 @nekomiao123 
Did retraining help?
As I have heard from other users that retraining helped to workaround this issue. I believe @jhonatantirado  also confirmed this.
Please let me know and I can close this issue.

**Comment by jhonatantirado** [comment] 2019-06-13 13:58
Yes, retraining the model fixed the issue for me.

**Comment by nekomiao123** [comment] 2019-06-13 14:12
Yes，I fixed this issue by retraining the model

**Closed** 2019-06-15 08:13 UTC
